export type SiteLang = 'zh' | 'en';

export const SITE_COPY = {
  zh: {
    siteName: 'Incremental Findings 增量发现',
    tagline: '独立研究档案 · 面向可复现证据与高质量编辑流程',
    nav: {
      home: '首页',
      submit: '投稿',
      community: '使命与计划',
      editor: '编辑部',
      account: '账户',
      login: '登录',
      logout: '退出登录'
    },
    home: {
      title: '发现可复现的增量研究',
      subtitle: '按分区、学科与稿件类型筛选，快速浏览学术稿与娱乐稿。',
      allTracks: '全部分区',
      allDisciplines: '全部学科',
      allTypes: '全部类型',
      clearFilters: '清空筛选',
      latestPublished: '最新发布',
      noPublishedTitle: '当前筛选下暂无已发布内容',
      noPublishedDesc: '目前仅展示已完成审稿并发布的稿件。你可以切换筛选，或直接提交新稿。',
      openArticle: '查看文章页',
      readPdf: '阅读 PDF',
      contributeTitle: '提交你的下一篇研究',
      contributeSubtitle: '先选择学术研讨区或自由创作区，再进入合适流程。',
      startSubmission: '开始投稿',
      manageAccount: '管理账户与 ORCID',
      openEditor: '进入编辑部'
    },
    community: {
      title: '期刊使命与公开计划',
      subtitle: '面向群众、面向研究者、面向可复现证据：这是我们期刊的公开目标。'
    },
    login: {
      title: '作者与编辑访问',
      subtitle: '作者用于投稿，编辑使用专属访问码进入审稿工作台。',
      authorLogin: '作者登录',
      authorRegister: '作者注册',
      editorLogin: '编辑登录',
      editorApply: '申请成为审稿编辑',
      applyDescription: '提交审稿编辑申请，并等待行政编辑审核后签发专属邀请访问码。',
      applyCurrentAccount: '当前登录账号',
      applyNoAccount: '未登录',
      applyNeedsAuth: '请先完成作者登录或作者注册，再提交审稿编辑申请。',
      applyStatement: '申请说明',
      applyPlaceholder: '请介绍你的研究方向、审稿经验和可投入时间（至少20字）',
      applySubmit: '提交审稿编辑申请',
      applySuccess: '审稿编辑申请已提交，请等待行政编辑审核。',
      applyReused: '你已有待处理的审稿编辑申请，请等待审核。',
      applyMinLength: '申请说明至少需要 20 个字符。',
      applyHint: '提示：行政编辑使用环境编辑码登录；审稿编辑需先申请并使用邀请码登录。',
      name: '姓名',
      namePlaceholder: '你的真实姓名',
      usernameOptional: '用户名（可选）',
      usernamePlaceholder: 'your_handle',
      email: '邮箱',
      emailOrUsername: '邮箱或用户名',
      emailPlaceholder: 'you@research.org 或 your_username',
      editorEmailPlaceholder: 'editor@journal.org',
      editorRole: '编辑角色',
      managingEditorRoleOption: '行政编辑',
      reviewEditorRoleOption: '审稿编辑',
      editorAccessCode: '编辑访问码',
      editorCodePlaceholder: '由管理员提供',
      editorInviteCode: '审稿邀请码',
      editorInviteCodePlaceholder: '由行政编辑签发',
      editorOrInviteDivider: '或使用审稿邀请码登录',
      editorNeedsCredential: '请填写编辑访问码或审稿邀请码。',
      editorAccessIntro: '编辑入口分为两条路径，请根据你的角色选择对应方式：',
      managingEditorTitle: '行政编辑入口',
      managingEditorBody: '直接使用环境编辑码登录（EDITOR_ACCESS_CODE）。如需要轮换可配置 EDITOR_ACCESS_CODE_ROLLOVER。',
      reviewEditorTitle: '审稿编辑入口',
      reviewEditorBody: '先提交审稿编辑申请，等待行政编辑审核并签发邀请码后，再返回此页使用邀请码登录。',
      reviewEditorCta: '去申请审稿编辑',
      password: '密码',
      processing: '处理中...',
      createAccount: '创建账户',
      enterWorkspace: '进入编辑工作台',
      signIn: '登录',
      editorHint: '行政编辑使用 EDITOR_ACCESS_CODE 登录；审稿编辑使用行政编辑签发的邀请码登录。两个入口可并列使用。',
      failedPrefix: '失败：',
      registerSuccess: '注册成功。',
      verificationPrompt: '请先发送邮箱验证码，并在创建账户前填写收到的 6 位验证码。',
      sendVerificationCode: '发送邮箱验证码',
      verificationCode: '邮箱验证码',
      verificationCodePlaceholder: '输入 6 位验证码',
      verifyCodeButton: '验证邮箱',
      resendVerification: '重新发送验证码',
      codeSentSuccess: '邮箱验证码已发送，请填写后再创建账户。',
      verificationSuccess: '邮箱验证成功。',
      registerNeedsEmail: '请先输入邮箱后再发送验证码。',
      registerNeedsCode: '请先发送邮箱验证码并填写收到的 6 位验证码。',
      loginNeedsVerification: '邮箱尚未验证，请先完成邮箱验证码验证。',
      editorSuccess: '编辑登录成功。',
      loginSuccess: '登录成功。'
    },
    submit: {
      title: '投稿门户',
      subtitle: '在进入编辑初筛前，先选择投稿分区，并完成身份、合规与文件完整性校验。',
      workflowTitle: '流程总览',
      steps: [
        '账户登录 + 可选 ORCID 绑定',
        '作者协议与合规声明',
        '稿件元数据填写（分区/题目/作者/学科/主题/稿件类型）',
        '文件包上传（主文稿 + 投稿信 + 可选附件）',
        '提交回执 + 编辑流程推进（under_review → accepted / rejected → in_production → published）'
      ],
      draftHint: '提示：身份信息会从当前会话预填。请先选择学术研讨区或自由创作区，并补齐所有必填字段后再提交。',
      authorIdentity: '1) 作者身份',
      yourEmail: '你的账户邮箱',
      authorOrcid: '作者 ORCID',
      manageOrcid: '管理 ORCID / 账户',
      agreement: '2) 作者协议（必填）',
      termsVersion: '协议版本',
      protocolAck: '我已阅读并理解完整作者协议与审稿流程要求。',
      metadata: '3) 稿件元数据与分区',
      submissionTrack: '投稿分区',
      trackAcademic: '学术研讨区',
      trackEntertainment: '自由创作区',
      trackAcademicHint: '适用于增量研究、重复研究、阴性结果、方法改进与可申请正式 DOI 的讨论稿。',
      trackEntertainmentHint: '适用于评论、随笔、科普和实验性表达；重点审核合法合规与版权，不自动分配 DOI。',
      versionPolicyTitle: '版本 / DOI 规则',
      versionPolicyAcademic: '学术研讨区：V1 可作为讨论稿公开，修订达标后可申请正式版 DOI；DOI 仅指向最终定稿版。',
      versionPolicyEntertainment: '自由创作区：内容可公开讨论与展示，但默认不分配 DOI，也不进入正式学术出版流程。',
      rightsPolicyAcademic: '学术研讨区：讨论版期间作者保留版权；如申请转正并被接收，平台对正式版保留优先出版权。',
      rightsPolicyEntertainment: '自由创作区：作者保留版权，平台保留公开展示、存档与审计记录所需权利。',
      titleField: '标题',
      authorsField: '作者（逗号分隔）',
      discipline: '学科',
      topic: '主题',
      articleType: '稿件类型',
      abstractField: '摘要',
      upload: '4) 文件包上传',
      manuscript: '主文稿 PDF（必填）',
      coverLetter: '投稿信（必填）',
      supporting: '补充材料（可选，多文件）',
      submitting: '提交中...',
      submitButton: '提交完整包',
      eta: '预计编辑初筛反馈：5–7 个工作日；学术区 DOI 需作者申请并经编辑审核后触发。',
      failedPrefix: '投稿失败：',
      success: '投稿创建成功。',
      warningPrefix: '警告：'
    },
    account: {
      welcome: '欢迎回来',
      subtitle: '投稿前请在此管理身份、ORCID 与同意记录。',
      identityTitle: '身份与研究者资料',
      email: '邮箱',
      notLoggedIn: '未登录',
      orcid: 'ORCID',
      notConnected: '未连接',
      reconnectOrcid: '重新连接 ORCID',
      connectOrcid: '连接 ORCID',
      logout: '退出登录',
      checklistTitle: '作者合规清单',
      checklist: [
        '使用已验证邮箱账户。',
        '建议绑定 ORCID 以保持身份一致。',
        '投稿时同意作者协议与伦理声明。',
        '保持主文稿、投稿信与附件可追溯。'
      ],
      quickActions: '快捷操作',
      startSubmission: '开始新投稿',
      openEditor: '打开编辑工作台',
      switchAccount: '切换账户',
      diagnostics: '运行 ORCID 诊断',
      pleaseLoginFirst: '请先登录。',
      redirectingOrcid: '正在跳转 ORCID… 若该账号已授权，ORCID 可能直接返回。',
      orcidConnected: 'ORCID 连接成功。',
      orcidFailed: 'ORCID 连接失败：',
      orcidFailedGeneric: 'ORCID 连接失败。',
      couldNotStart: '无法启动 ORCID 流程',
      loggedOut: '你已退出登录。',
      diagnosticsFailed: '无法加载诊断信息。',
      applyEditorLoginFirst: '请先登录后再提交编辑申请。',
      applyEditorMinLength: '申请说明至少需要 20 个字符。',
      applyEditorTitle: '申请成为审稿编辑',
      applyEditorDescription: '提交你的背景说明后，行政编辑可在工作台审核并手动发放审稿编辑邀请访问码。',
      applyEditorPlaceholder: '请填写研究方向、审稿经验、每周可投入时间等信息（至少20字）',
      applyEditorSubmit: '提交审稿编辑申请',
      applyEditorFailedPrefix: '提交失败：',
      applyEditorReused: '你已有待处理的审稿编辑申请，请耐心等待。',
      applyEditorSuccess: '审稿编辑申请已提交，等待行政编辑审核与邀请。'
    },
    editor: {
      checkingAuthorization: '正在检查编辑权限…',
      loginRequiredTitle: '需要编辑登录',
      loginRequiredDesc: '当前工作台仅开放给编辑账号。请通过登录页的编辑登录入口，使用访问码或邀请访问码进入审稿系统。',
      goToLogin: '前往编辑登录',
      workspaceTitle: '编辑工作台',
      workspaceSubtitle: '在一个页面管理初筛、外审流程与发布决策。',
      pendingMetric: '待处理',
      underReviewMetric: '审稿中',
      publishedMetric: '已发布',
      activeQueueMetric: '活跃队列',
      searchPlaceholder: '搜索标题、作者、摘要或主题',
      allTracks: '全部分区',
      allDisciplines: '全部学科',
      resetFilters: '重置筛选',
      loadFailedPrefix: '加载失败：',
      applicationsTitle: '编辑申请',
      applicationsSubtitle: '审核审稿编辑申请并签发邀请码。',
      noPendingApplications: '暂无待处理申请。',
      approveAndInvite: '通过为审稿编辑并生成邀请',
      inviteFailedPrefix: '邀请失败：',
      inviteCreatedPrefix: '已生成邀请访问码（请手动发送给申请人）：',
      inviteCreated: '邀请已创建。',
      submissionsInProgress: '投稿处理中',
      noPendingSubmissions: '暂无待处理投稿。',
      noAbstract: '暂无摘要。',
      moveToUnderReview: '转入审稿中',
      reject: '拒稿',
      rejectPrompt: '请填写拒稿原因（必填）',
      rejectReasonRequired: '拒稿必须填写原因。',
      updateStatusFailedPrefix: '状态更新失败：',
      updateStatusSuccessPrefix: '状态已更新为 ',
      peerReviewQueue: '同行评审队列',
      noUnderReviewSubmissions: '暂无审稿中的投稿。',
      publish: '发布',
      publishedWork: '已发布稿件',
      noPublishedSubmissions: '暂无已发布稿件。',
      viewPdf: '查看 PDF',
      publicationIdPrefix: '发布编号：',
      assignPublicationId: '分配发布编号',
      assignDoiFailedPrefix: '编号分配失败：',
      publicationIdAssignedPrefix: '发布编号已分配：',
      identifierAssigned: '编号分配完成。',
      unclassified: '未分类'
    },
    paperCard: {
      noAbstract: '暂无摘要。',
      openArticle: '查看文章',
      pdf: 'PDF'
    },
    paperDetail: {
      notFound: '论文未找到 · Incremental Findings',
      publishedArticle: '已发布论文',
      doiPending: '讨论版：可在定稿后申请 DOI',
      entertainmentNote: '自由创作区内容，不分配 DOI。',
      versionHistory: '版本说明',
      versionHistoryAcademic: '本页可能对应公开讨论稿（如 V1/V2）。若后续形成正式版，DOI 仅指向最终定稿版，讨论版继续保留为历史记录。',
      versionHistoryEntertainment: '本页为自由创作区公开版本，可继续修订或替换展示，但默认不进入正式 DOI 出版流程。',
      abstract: '摘要',
      noAbstract: '暂无摘要。',
      viewPdf: '查看全文 PDF',
      downloadBibtex: '下载 BibTeX',
      backToDiscovery: '返回发现页'
    }
  },
  en: {
    siteName: 'Incremental Findings',
    tagline: 'Independent research archive · Reproducible evidence with strong editorial workflow',
    nav: {
      home: 'Home',
      submit: 'Submit',
      community: 'Mission & Plan',
      editor: 'Editorial',
      account: 'Account',
      login: 'Log in',
      logout: 'Log out'
    },
    home: {
      title: 'Discover reproducible incremental research',
      subtitle: 'Filter by track, discipline, and article type to browse academic and creative outputs.',
      allTracks: 'All tracks',
      allDisciplines: 'All disciplines',
      allTypes: 'All types',
      clearFilters: 'Clear filters',
      latestPublished: 'Latest published',
      noPublishedTitle: 'No published papers under this filter',
      noPublishedDesc: 'Only reviewed and published papers are shown. Try a different filter or submit a new manuscript.',
      openArticle: 'Open article page',
      readPdf: 'Read PDF',
      contributeTitle: 'Contribute your next finding',
      contributeSubtitle: 'Choose the academic review track or the creative/entertainment track before you submit.',
      startSubmission: 'Start a submission',
      manageAccount: 'Manage account & ORCID',
      openEditor: 'Open editorial workspace'
    },
    community: {
      title: 'Journal Mission & Public Plan',
      subtitle: 'For the public, for researchers, and for reproducible evidence: our open journal commitment.'
    },
    login: {
      title: 'Author & editor access',
      subtitle: 'Authors use this for submissions; editors use a dedicated access code.',
      authorLogin: 'Author Log in',
      authorRegister: 'Author Register',
      editorLogin: 'Editor Log in',
      editorApply: 'Apply as Review Editor',
      applyDescription: 'Submit a review-editor application and wait for a managing editor to issue an invitation code.',
      applyCurrentAccount: 'Current account',
      applyNoAccount: 'Not logged in',
      applyNeedsAuth: 'Please complete author login/registration before submitting a review-editor application.',
      applyStatement: 'Application statement',
      applyPlaceholder: 'Describe your discipline, review experience and availability (min 20 chars).',
      applySubmit: 'Submit review-editor application',
      applySuccess: 'Review-editor application submitted. Please wait for managing editor review.',
      applyReused: 'You already have a pending review-editor application. Please wait for review.',
      applyMinLength: 'Application statement must be at least 20 characters.',
      applyHint: 'Tip: managing editors use the environment access code; review editors should apply first and then sign in with an invitation code.',
      name: 'Name',
      namePlaceholder: 'Your full name',
      usernameOptional: 'Username (optional)',
      usernamePlaceholder: 'your_handle',
      email: 'Email',
      emailOrUsername: 'Email or username',
      emailPlaceholder: 'you@research.org or your_username',
      editorEmailPlaceholder: 'editor@journal.org',
      editorRole: 'Editor role',
      managingEditorRoleOption: 'Managing editor',
      reviewEditorRoleOption: 'Review editor',
      editorAccessCode: 'Editor access code',
      editorCodePlaceholder: 'Provided by admin',
      editorInviteCode: 'Review invite code',
      editorInviteCodePlaceholder: 'Issued by managing editor',
      editorOrInviteDivider: 'Or sign in with a review invite code',
      editorNeedsCredential: 'Please provide an editor access code or a review invite code.',
      editorAccessIntro: 'The editorial workspace has two entry paths. Pick the one that matches your role:',
      managingEditorTitle: 'Managing editor entry',
      managingEditorBody: 'Sign in directly with the environment access code (EDITOR_ACCESS_CODE). Use EDITOR_ACCESS_CODE_ROLLOVER for credential rotation.',
      reviewEditorTitle: 'Review editor entry',
      reviewEditorBody: 'Apply first, wait for a managing editor to approve you and issue an invitation code, then return here and sign in with that invite.',
      reviewEditorCta: 'Apply for review editor access',
      password: 'Password',
      processing: 'Processing...',
      createAccount: 'Create account',
      enterWorkspace: 'Enter editorial workspace',
      signIn: 'Sign in',
      editorHint: 'Managing editors sign in with EDITOR_ACCESS_CODE; review editors sign in with invite codes issued by managing editors. Both paths are supported in parallel.',
      failedPrefix: 'Failed: ',
      registerSuccess: 'Registration successful.',
      verificationPrompt: 'Please send an email verification code first, then enter the 6-digit code before creating the account.',
      sendVerificationCode: 'Send verification code',
      verificationCode: 'Email verification code',
      verificationCodePlaceholder: 'Enter 6-digit code',
      verifyCodeButton: 'Verify email',
      resendVerification: 'Resend verification code',
      codeSentSuccess: 'Verification code sent. Enter it before creating your account.',
      verificationSuccess: 'Email verified successfully.',
      registerNeedsEmail: 'Enter your email address before requesting a verification code.',
      registerNeedsCode: 'Send a verification code and enter the 6-digit code before creating your account.',
      loginNeedsVerification: 'Your email is not verified yet. Please complete email verification first.',
      editorSuccess: 'Editor login successful.',
      loginSuccess: 'Login successful.'
    },
    submit: {
      title: 'Submission Portal',
      subtitle: 'A guided pipeline where you first choose a submission track, then complete identity, compliance, and package integrity checks before editorial screening.',
      workflowTitle: 'Workflow overview',
      steps: [
        'Account login + optional ORCID linking',
        'Author agreement and compliance declaration',
        'Metadata entry (track/title/authors/discipline/topic/type)',
        'File package upload (manuscript + cover letter + optional supporting files)',
        'Submission receipt + editorial progression (under_review → accepted / rejected → in_production → published)'
      ],
      draftHint: 'Draft hint: your account identity is prefilled from local session. Choose the academic or creative track first, then complete every required field before submitting.',
      authorIdentity: '1) Author identity',
      yourEmail: 'Your account email',
      authorOrcid: 'Author ORCID',
      manageOrcid: 'Manage ORCID / Account',
      agreement: '2) Author agreement (required)',
      termsVersion: 'Terms version',
      protocolAck: 'I have read and understood the full author agreement and review workflow requirements.',
      metadata: '3) Track & manuscript metadata',
      submissionTrack: 'Submission track',
      trackAcademic: 'Academic review track',
      trackEntertainment: 'Creative / entertainment track',
      trackAcademicHint: 'For incremental research, replications, negative findings, methods work, and discussion drafts that may later request a formal DOI.',
      trackEntertainmentHint: 'For commentary, essays, science communication, and experimental expression; reviewed mainly for legality, safety, and rights, without automatic DOI assignment.',
      versionPolicyTitle: 'Version / DOI rules',
      versionPolicyAcademic: 'Academic track: V1 may appear as a discussion draft; after adequate revision, the author may request a DOI for the formal version of record only.',
      versionPolicyEntertainment: 'Creative track: pieces may be publicly discussed and displayed, but they do not receive a DOI by default and do not enter the formal scholarly publishing path.',
      rightsPolicyAcademic: 'Academic track: authors keep copyright during discussion-stage review; if a formal version is accepted, the platform retains first-publication priority for that version.',
      rightsPolicyEntertainment: 'Creative track: authors retain copyright while the platform keeps the rights needed for public display, archiving, and audit history.',
      titleField: 'Title',
      authorsField: 'Authors (comma-separated)',
      discipline: 'Discipline',
      topic: 'Topic',
      articleType: 'Article type',
      abstractField: 'Abstract',
      upload: '4) File package upload',
      manuscript: 'Manuscript PDF (required)',
      coverLetter: 'Cover letter (required)',
      supporting: 'Supporting materials (optional, multiple)',
      submitting: 'Submitting...',
      submitButton: 'Submit complete package',
      eta: 'Estimated editorial triage feedback: within 5–7 business days; academic-track DOI assignment is author-triggered and editor-approved.',
      failedPrefix: 'Submission failed: ',
      success: 'Submission created successfully.',
      warningPrefix: 'Warnings: '
    },
    account: {
      welcome: 'Welcome back',
      subtitle: 'Identity, ORCID and consent records are managed here before submissions.',
      identityTitle: 'Identity and research profile',
      email: 'Email',
      notLoggedIn: 'Not logged in',
      orcid: 'ORCID',
      notConnected: 'Not connected',
      reconnectOrcid: 'Reconnect ORCID',
      connectOrcid: 'Connect ORCID',
      logout: 'Log out',
      checklistTitle: 'Author compliance checklist',
      checklist: [
        'Use a verified email account.',
        'Link ORCID for identity consistency (recommended).',
        'Accept author agreement and ethics declarations at submission time.',
        'Keep manuscript, cover letter and supporting files traceable.'
      ],
      quickActions: 'Quick actions',
      startSubmission: 'Start new submission',
      openEditor: 'Open editorial workspace',
      switchAccount: 'Switch account',
      diagnostics: 'Run ORCID diagnostics',
      pleaseLoginFirst: 'Please login first.',
      redirectingOrcid: 'Redirecting to ORCID… if this account already authorized before, ORCID may return directly.',
      orcidConnected: 'ORCID connected.',
      orcidFailed: 'ORCID connection failed: ',
      orcidFailedGeneric: 'ORCID connection failed.',
      couldNotStart: 'Could not start ORCID flow',
      loggedOut: 'You have been logged out.',
      diagnosticsFailed: 'Could not load diagnostics.',
      applyEditorLoginFirst: 'Please log in before submitting an editor application.',
      applyEditorMinLength: 'Application statement must be at least 20 characters.',
      applyEditorTitle: 'Apply to become a review editor',
      applyEditorDescription: 'After you submit your background statement, managing editors can review it and issue a manual review-editor invitation code.',
      applyEditorPlaceholder: 'Describe your research area, review experience, and weekly availability (at least 20 characters).',
      applyEditorSubmit: 'Submit review-editor application',
      applyEditorFailedPrefix: 'Submission failed: ',
      applyEditorReused: 'You already have a pending review-editor application. Please wait for review.',
      applyEditorSuccess: 'Review-editor application submitted. Please wait for managing-editor review and invite.'
    },
    editor: {
      checkingAuthorization: 'Checking editorial authorization…',
      loginRequiredTitle: 'Editorial login required',
      loginRequiredDesc: 'This workspace is only available to editor accounts. Please use editor login on the login page with an access code or invitation code.',
      goToLogin: 'Go to editor login',
      workspaceTitle: 'Editorial Workspace',
      workspaceSubtitle: 'Manage screening, review progression and publishing decisions in one place.',
      pendingMetric: 'Pending',
      underReviewMetric: 'Under review',
      publishedMetric: 'Published',
      activeQueueMetric: 'Active queue',
      searchPlaceholder: 'Search title, authors, abstract, topic',
      allTracks: 'All tracks',
      allDisciplines: 'All disciplines',
      resetFilters: 'Reset filters',
      loadFailedPrefix: 'Load failed: ',
      applicationsTitle: 'Editor applications',
      applicationsSubtitle: 'Review incoming review-editor requests and issue invitation codes.',
      noPendingApplications: 'No pending applications.',
      approveAndInvite: 'Approve as review editor & invite',
      inviteFailedPrefix: 'Invite failed: ',
      inviteCreatedPrefix: 'Invite code generated (send manually to applicant): ',
      inviteCreated: 'Invite created.',
      submissionsInProgress: 'Submissions in progress',
      noPendingSubmissions: 'No pending submissions.',
      noAbstract: 'No abstract provided.',
      moveToUnderReview: 'Move to under review',
      reject: 'Reject',
      rejectPrompt: 'Please provide rejection reason (required)',
      rejectReasonRequired: 'Rejection reason is required.',
      updateStatusFailedPrefix: 'Status update failed: ',
      updateStatusSuccessPrefix: 'Status updated to ',
      peerReviewQueue: 'Peer review queue',
      noUnderReviewSubmissions: 'No submissions under review.',
      publish: 'Publish',
      publishedWork: 'Published work',
      noPublishedSubmissions: 'No published submissions.',
      viewPdf: 'View PDF',
      publicationIdPrefix: 'Publication ID: ',
      assignPublicationId: 'Assign Publication ID',
      assignDoiFailedPrefix: 'Identifier assignment failed: ',
      publicationIdAssignedPrefix: 'Publication ID assigned: ',
      identifierAssigned: 'Identifier assignment completed.',
      unclassified: 'Unclassified'
    },
    paperCard: {
      noAbstract: 'No abstract provided.',
      openArticle: 'Open article',
      pdf: 'PDF'
    },
    paperDetail: {
      notFound: 'Paper not found · Incremental Findings',
      publishedArticle: 'Published paper',
      doiPending: 'Discussion version: DOI may be requested after the final version is ready',
      entertainmentNote: 'Creative/entertainment track content does not receive a DOI.',
      versionHistory: 'Version note',
      versionHistoryAcademic: 'This page may represent a public discussion draft (such as V1/V2). If a formal version is later published, the DOI points only to the final version of record while the discussion draft remains as traceable history.',
      versionHistoryEntertainment: 'This page is a public creative-track version. It may continue to evolve, but it does not enter the formal DOI publication workflow by default.',
      abstract: 'Abstract',
      noAbstract: 'No abstract provided.',
      viewPdf: 'View full PDF',
      downloadBibtex: 'Download BibTeX',
      backToDiscovery: 'Back to discovery'
    }
  }
} as const;

export function getSiteLang(input?: string | null): SiteLang {
  return input === 'en' ? 'en' : 'zh';
}

export function getSiteCopy(lang?: string | null) {
  return SITE_COPY[getSiteLang(lang)];
}
