export type SiteLang = 'zh' | 'en';

export const SITE_COPY = {
  zh: {
    siteName: 'Incremental Findings 增量发现',
    tagline: '独立研究档案 · 面向可复现证据与高质量编辑流程',
    nav: {
      home: '首页',
      submit: '投稿',
      community: '使命与计划',
      editor: '编辑部',
      account: '账户',
      login: '登录',
      logout: '退出登录'
    },
    home: {
      title: '发现可复现的增量研究',
      subtitle: '按学科与稿件类型筛选，快速浏览高信号论文。',
      allDisciplines: '全部学科',
      allTypes: '全部类型',
      clearFilters: '清空筛选',
      latestPublished: '最新发布',
      noPublishedTitle: '当前筛选下暂无已发布内容',
      noPublishedDesc: '目前仅展示已完成审稿并发布的稿件。你可以切换筛选，或直接提交新稿。',
      openArticle: '查看文章页',
      readPdf: '阅读 PDF',
      contributeTitle: '提交你的下一篇研究',
      contributeSubtitle: '根据你的当前阶段，选择合适入口。',
      startSubmission: '开始投稿',
      manageAccount: '管理账户与 ORCID',
      openEditor: '进入编辑部'
    },
    community: {
      title: '期刊使命与公开计划',
      subtitle: '面向群众、面向研究者、面向可复现证据：这是我们期刊的公开目标。'
    },
    login: {
      title: '作者与编辑访问',
      subtitle: '作者用于投稿，编辑使用专属访问码进入审稿工作台。',
      authorLogin: '作者登录',
      authorRegister: '作者注册',
      editorLogin: '编辑登录',
      editorApply: '编辑申请',
      applyDescription: '提交编辑申请并等待行政编辑签发邀请访问码。',
      applyCurrentAccount: '当前登录账号',
      applyNoAccount: '未登录',
      applyNeedsAuth: '请先完成作者登录或作者注册，再提交编辑申请。',
      applyStatement: '申请说明',
      applyPlaceholder: '请介绍你的研究方向、审稿经验和可投入时间（至少20字）',
      applySubmit: '提交编辑申请',
      applySuccess: '编辑申请已提交，请等待行政编辑审核。',
      applyReused: '你已有待处理的编辑申请，请等待审核。',
      applyMinLength: '申请说明至少需要 20 个字符。',
      applyHint: '提示：编辑登录使用专属访问码；申请通过后会获得邀请码或专属编辑码。',
      name: '姓名',
      namePlaceholder: '你的真实姓名',
      usernameOptional: '用户名（可选）',
      usernamePlaceholder: 'your_handle',
      email: '邮箱',
      emailOrUsername: '邮箱或用户名',
      emailPlaceholder: 'you@research.org 或 your_username',
      editorEmailPlaceholder: 'editor@journal.org',
      editorAccessCode: '编辑访问码',
      editorCodePlaceholder: '由管理员提供',
      password: '密码',
      processing: '处理中...',
      createAccount: '创建账户',
      enterWorkspace: '进入编辑工作台',
      signIn: '登录',
      editorHint: '演示环境默认编辑码为 review-demo；生产环境可使用 EDITOR_ACCESS_CODE，或由现有编辑发放邀请访问码。',
      failedPrefix: '失败：',
      registerSuccess: '注册成功。',
      verificationPrompt: '请先发送邮箱验证码，并在创建账户前填写收到的 6 位验证码。',
      sendVerificationCode: '发送邮箱验证码',
      verificationCode: '邮箱验证码',
      verificationCodePlaceholder: '输入 6 位验证码',
      verifyCodeButton: '验证邮箱',
      resendVerification: '重新发送验证码',
      codeSentSuccess: '邮箱验证码已发送，请填写后再创建账户。',
      verificationSuccess: '邮箱验证成功。',
      registerNeedsEmail: '请先输入邮箱后再发送验证码。',
      registerNeedsCode: '请先发送邮箱验证码并填写收到的 6 位验证码。',
      loginNeedsVerification: '邮箱尚未验证，请先完成邮箱验证码验证。',
      editorSuccess: '编辑登录成功。',
      loginSuccess: '登录成功。'
    },
    submit: {
      title: '投稿门户',
      subtitle: '在进入编辑初筛前，先完成身份、合规与文件完整性校验。',
      workflowTitle: '流程总览',
      steps: [
        '账户登录 + 可选 ORCID 绑定',
        '作者协议与合规声明',
        '稿件元数据填写（题目/作者/学科/主题/稿件类型）',
        '文件包上传（主文稿 + cover letter + 可选附件）',
        '提交回执 + 编辑流程推进（pending → under_review → decision）'
      ],
      draftHint: '提示：身份信息会从当前会话预填，请先补齐所有必填文件字段再提交。',
      authorIdentity: '1) 作者身份',
      yourEmail: '你的账户邮箱',
      authorOrcid: '作者 ORCID',
      manageOrcid: '管理 ORCID / 账户',
      agreement: '2) 作者协议（必填）',
      termsVersion: '协议版本',
      protocolAck: '我已阅读并理解完整作者协议与审稿流程要求。',
      metadata: '3) 稿件元数据',
      titleField: '标题',
      authorsField: '作者（逗号分隔）',
      discipline: '学科',
      topic: '主题',
      articleType: '稿件类型',
      abstractField: '摘要',
      upload: '4) 文件包上传',
      manuscript: '主文稿 PDF（必填）',
      coverLetter: '投稿信（必填）',
      supporting: '补充材料（可选，多文件）',
      submitting: '提交中...',
      submitButton: '提交完整包',
      eta: '预计编辑初筛反馈：5–7 个工作日。',
      failedPrefix: '投稿失败：',
      success: '投稿创建成功。',
      warningPrefix: '警告：'
    },
    account: {
      welcome: '欢迎回来',
      subtitle: '投稿前请在此管理身份、ORCID 与同意记录。',
      identityTitle: '身份与研究者资料',
      email: '邮箱',
      notLoggedIn: '未登录',
      orcid: 'ORCID',
      notConnected: '未连接',
      reconnectOrcid: '重新连接 ORCID',
      connectOrcid: '连接 ORCID',
      logout: '退出登录',
      checklistTitle: '作者合规清单',
      checklist: [
        '使用已验证邮箱账户。',
        '建议绑定 ORCID 以保持身份一致。',
        '投稿时同意作者协议与伦理声明。',
        '保持主文稿、投稿信与附件可追溯。'
      ],
      quickActions: '快捷操作',
      startSubmission: '开始新投稿',
      openEditor: '打开编辑工作台',
      switchAccount: '切换账户',
      diagnostics: '运行 ORCID 诊断',
      pleaseLoginFirst: '请先登录。',
      redirectingOrcid: '正在跳转 ORCID… 若该账号已授权，ORCID 可能直接返回。',
      orcidConnected: 'ORCID 连接成功。',
      orcidFailed: 'ORCID 连接失败：',
      orcidFailedGeneric: 'ORCID 连接失败。',
      couldNotStart: '无法启动 ORCID 流程',
      loggedOut: '你已退出登录。',
      diagnosticsFailed: '无法加载诊断信息。',
      applyEditorLoginFirst: '请先登录后再提交编辑申请。',
      applyEditorMinLength: '申请说明至少需要 20 个字符。',
      applyEditorTitle: '申请成为编辑',
      applyEditorDescription: '提交你的背景说明后，现有编辑可在工作台审核并手动发放编辑邀请访问码。',
      applyEditorPlaceholder: '请填写研究方向、审稿经验、每周可投入时间等信息（至少20字）',
      applyEditorSubmit: '提交编辑申请',
      applyEditorFailedPrefix: '提交失败：',
      applyEditorReused: '你已有待处理的编辑申请，请耐心等待。',
      applyEditorSuccess: '编辑申请已提交，等待现有编辑审核与邀请。'
    },
    editor: {
      checkingAuthorization: '正在检查编辑权限…',
      loginRequiredTitle: '需要编辑登录',
      loginRequiredDesc: '当前工作台仅开放给编辑账号。请通过登录页的编辑登录入口，使用访问码或邀请访问码进入审稿系统。',
      goToLogin: '前往编辑登录',
      workspaceTitle: '编辑工作台',
      workspaceSubtitle: '在一个页面管理初筛、外审流程与发布决策。',
      pendingMetric: '待处理',
      underReviewMetric: '审稿中',
      publishedMetric: '已发布',
      activeQueueMetric: '活跃队列',
      searchPlaceholder: '搜索标题、作者、摘要或主题',
      allDisciplines: '全部学科',
      resetFilters: '重置筛选',
      loadFailedPrefix: '加载失败：',
      applicationsTitle: '编辑申请',
      applicationsSubtitle: '审核编辑申请并签发邀请访问码。',
      noPendingApplications: '暂无待处理申请。',
      approveAndInvite: '通过并生成邀请',
      inviteFailedPrefix: '邀请失败：',
      inviteCreatedPrefix: '已生成邀请访问码（请手动发送给申请人）：',
      inviteCreated: '邀请已创建。',
      submissionsInProgress: '投稿处理中',
      noPendingSubmissions: '暂无待处理投稿。',
      noAbstract: '暂无摘要。',
      moveToUnderReview: '转入审稿中',
      reject: '拒稿',
      rejectPrompt: '请填写拒稿原因（必填）',
      rejectReasonRequired: '拒稿必须填写原因。',
      updateStatusFailedPrefix: '状态更新失败：',
      updateStatusSuccessPrefix: '状态已更新为 ',
      peerReviewQueue: '同行评审队列',
      noUnderReviewSubmissions: '暂无审稿中的投稿。',
      publish: '发布',
      publishedWork: '已发布稿件',
      noPublishedSubmissions: '暂无已发布稿件。',
      viewPdf: '查看 PDF',
      publicationIdPrefix: '发布编号：',
      assignPublicationId: '分配发布编号',
      assignDoiFailedPrefix: '编号分配失败：',
      publicationIdAssignedPrefix: '发布编号已分配：',
      identifierAssigned: '编号分配完成。',
      unclassified: '未分类'
    },
    paperCard: {
      noAbstract: '暂无摘要。',
      openArticle: '查看文章',
      pdf: 'PDF'
    },
    paperDetail: {
      notFound: '论文未找到 · Incremental Findings',
      publishedArticle: '已发布论文',
      doiPending: 'DOI 待分配',
      abstract: '摘要',
      noAbstract: '暂无摘要。',
      viewPdf: '查看全文 PDF',
      downloadBibtex: '下载 BibTeX',
      backToDiscovery: '返回发现页'
    }
  },
  en: {
    siteName: 'Incremental Findings',
    tagline: 'Independent research archive · Reproducible evidence with strong editorial workflow',
    nav: {
      home: 'Home',
      submit: 'Submit',
      community: 'Mission & Plan',
      editor: 'Editorial',
      account: 'Account',
      login: 'Log in',
      logout: 'Log out'
    },
    home: {
      title: 'Discover reproducible incremental research',
      subtitle: 'Filter by discipline and article type to quickly browse high-signal papers.',
      allDisciplines: 'All disciplines',
      allTypes: 'All types',
      clearFilters: 'Clear filters',
      latestPublished: 'Latest published',
      noPublishedTitle: 'No published papers under this filter',
      noPublishedDesc: 'Only reviewed and published papers are shown. Try a different filter or submit a new manuscript.',
      openArticle: 'Open article page',
      readPdf: 'Read PDF',
      contributeTitle: 'Contribute your next finding',
      contributeSubtitle: 'Choose the right entry based on your current workflow stage.',
      startSubmission: 'Start a submission',
      manageAccount: 'Manage account & ORCID',
      openEditor: 'Open editorial workspace'
    },
    community: {
      title: 'Journal Mission & Public Plan',
      subtitle: 'For the public, for researchers, and for reproducible evidence: our open journal commitment.'
    },
    login: {
      title: 'Author & editor access',
      subtitle: 'Authors use this for submissions; editors use a dedicated access code.',
      authorLogin: 'Author Log in',
      authorRegister: 'Author Register',
      editorLogin: 'Editor Log in',
      editorApply: 'Apply as Editor',
      applyDescription: 'Submit an editor application and wait for managing editor invitation code issuance.',
      applyCurrentAccount: 'Current account',
      applyNoAccount: 'Not logged in',
      applyNeedsAuth: 'Please complete author login/registration before submitting an editor application.',
      applyStatement: 'Application statement',
      applyPlaceholder: 'Describe your discipline, review experience and availability (min 20 chars).',
      applySubmit: 'Submit editor application',
      applySuccess: 'Editor application submitted. Please wait for managing editor review.',
      applyReused: 'You already have a pending editor application. Please wait for review.',
      applyMinLength: 'Application statement must be at least 20 characters.',
      applyHint: 'Tip: editor login uses a dedicated access code. After approval you will receive an invite code or dedicated editor code.',
      name: 'Name',
      namePlaceholder: 'Your full name',
      usernameOptional: 'Username (optional)',
      usernamePlaceholder: 'your_handle',
      email: 'Email',
      emailOrUsername: 'Email or username',
      emailPlaceholder: 'you@research.org or your_username',
      editorEmailPlaceholder: 'editor@journal.org',
      editorAccessCode: 'Editor access code',
      editorCodePlaceholder: 'Provided by admin',
      password: 'Password',
      processing: 'Processing...',
      createAccount: 'Create account',
      enterWorkspace: 'Enter editorial workspace',
      signIn: 'Sign in',
      editorHint: 'Demo default code is review-demo; use EDITOR_ACCESS_CODE in production, or an invite code issued by an existing editor.',
      failedPrefix: 'Failed: ',
      registerSuccess: 'Registration successful.',
      verificationPrompt: 'Please send an email verification code first, then enter the 6-digit code before creating the account.',
      sendVerificationCode: 'Send verification code',
      verificationCode: 'Email verification code',
      verificationCodePlaceholder: 'Enter 6-digit code',
      verifyCodeButton: 'Verify email',
      resendVerification: 'Resend verification code',
      codeSentSuccess: 'Verification code sent. Enter it before creating your account.',
      verificationSuccess: 'Email verified successfully.',
      registerNeedsEmail: 'Enter your email address before requesting a verification code.',
      registerNeedsCode: 'Send a verification code and enter the 6-digit code before creating your account.',
      loginNeedsVerification: 'Your email is not verified yet. Please complete email verification first.',
      editorSuccess: 'Editor login successful.',
      loginSuccess: 'Login successful.'
    },
    submit: {
      title: 'Submission Portal',
      subtitle: 'A guided pipeline with identity, compliance and package integrity checks before editorial screening.',
      workflowTitle: 'Workflow overview',
      steps: [
        'Account login + optional ORCID linking',
        'Author agreement and compliance declaration',
        'Metadata entry (title/authors/discipline/topic/type)',
        'File package upload (manuscript + cover letter + optional supporting files)',
        'Submission receipt + editor progression (pending → under_review → decision)'
      ],
      draftHint: 'Draft hint: your account identity is prefilled from local session. Complete all required file fields before submitting.',
      authorIdentity: '1) Author identity',
      yourEmail: 'Your account email',
      authorOrcid: 'Author ORCID',
      manageOrcid: 'Manage ORCID / Account',
      agreement: '2) Author agreement (required)',
      termsVersion: 'Terms version',
      protocolAck: 'I have read and understood the full author agreement and review workflow requirements.',
      metadata: '3) Manuscript metadata',
      titleField: 'Title',
      authorsField: 'Authors (comma-separated)',
      discipline: 'Discipline',
      topic: 'Topic',
      articleType: 'Article type',
      abstractField: 'Abstract',
      upload: '4) File package upload',
      manuscript: 'Manuscript PDF (required)',
      coverLetter: 'Cover letter (required)',
      supporting: 'Supporting materials (optional, multiple)',
      submitting: 'Submitting...',
      submitButton: 'Submit complete package',
      eta: 'Estimated editorial triage feedback: within 5–7 business days.',
      failedPrefix: 'Submission failed: ',
      success: 'Submission created successfully.',
      warningPrefix: 'Warnings: '
    },
    account: {
      welcome: 'Welcome back',
      subtitle: 'Identity, ORCID and consent records are managed here before submissions.',
      identityTitle: 'Identity and research profile',
      email: 'Email',
      notLoggedIn: 'Not logged in',
      orcid: 'ORCID',
      notConnected: 'Not connected',
      reconnectOrcid: 'Reconnect ORCID',
      connectOrcid: 'Connect ORCID',
      logout: 'Log out',
      checklistTitle: 'Author compliance checklist',
      checklist: [
        'Use a verified email account.',
        'Link ORCID for identity consistency (recommended).',
        'Accept author agreement and ethics declarations at submission time.',
        'Keep manuscript, cover letter and supporting files traceable.'
      ],
      quickActions: 'Quick actions',
      startSubmission: 'Start new submission',
      openEditor: 'Open editorial workspace',
      switchAccount: 'Switch account',
      diagnostics: 'Run ORCID diagnostics',
      pleaseLoginFirst: 'Please login first.',
      redirectingOrcid: 'Redirecting to ORCID… if this account already authorized before, ORCID may return directly.',
      orcidConnected: 'ORCID connected.',
      orcidFailed: 'ORCID connection failed: ',
      orcidFailedGeneric: 'ORCID connection failed.',
      couldNotStart: 'Could not start ORCID flow',
      loggedOut: 'You have been logged out.',
      diagnosticsFailed: 'Could not load diagnostics.',
      applyEditorLoginFirst: 'Please log in before submitting an editor application.',
      applyEditorMinLength: 'Application statement must be at least 20 characters.',
      applyEditorTitle: 'Apply to become an editor',
      applyEditorDescription: 'After you submit your background statement, existing editors can review it and issue a manual invitation code.',
      applyEditorPlaceholder: 'Describe your research area, review experience, and weekly availability (at least 20 characters).',
      applyEditorSubmit: 'Submit editor application',
      applyEditorFailedPrefix: 'Submission failed: ',
      applyEditorReused: 'You already have a pending editor application. Please wait for review.',
      applyEditorSuccess: 'Editor application submitted. Please wait for editor review and invite.'
    },
    editor: {
      checkingAuthorization: 'Checking editorial authorization…',
      loginRequiredTitle: 'Editorial login required',
      loginRequiredDesc: 'This workspace is only available to editor accounts. Please use editor login on the login page with an access code or invitation code.',
      goToLogin: 'Go to editor login',
      workspaceTitle: 'Editorial Workspace',
      workspaceSubtitle: 'Manage screening, review progression and publishing decisions in one place.',
      pendingMetric: 'Pending',
      underReviewMetric: 'Under review',
      publishedMetric: 'Published',
      activeQueueMetric: 'Active queue',
      searchPlaceholder: 'Search title, authors, abstract, topic',
      allDisciplines: 'All disciplines',
      resetFilters: 'Reset filters',
      loadFailedPrefix: 'Load failed: ',
      applicationsTitle: 'Editor applications',
      applicationsSubtitle: 'Review incoming editor requests and issue invitation codes.',
      noPendingApplications: 'No pending applications.',
      approveAndInvite: 'Approve & generate invite',
      inviteFailedPrefix: 'Invite failed: ',
      inviteCreatedPrefix: 'Invite code generated (send manually to applicant): ',
      inviteCreated: 'Invite created.',
      submissionsInProgress: 'Submissions in progress',
      noPendingSubmissions: 'No pending submissions.',
      noAbstract: 'No abstract provided.',
      moveToUnderReview: 'Move to under review',
      reject: 'Reject',
      rejectPrompt: 'Please provide rejection reason (required)',
      rejectReasonRequired: 'Rejection reason is required.',
      updateStatusFailedPrefix: 'Status update failed: ',
      updateStatusSuccessPrefix: 'Status updated to ',
      peerReviewQueue: 'Peer review queue',
      noUnderReviewSubmissions: 'No submissions under review.',
      publish: 'Publish',
      publishedWork: 'Published work',
      noPublishedSubmissions: 'No published submissions.',
      viewPdf: 'View PDF',
      publicationIdPrefix: 'Publication ID: ',
      assignPublicationId: 'Assign Publication ID',
      assignDoiFailedPrefix: 'Identifier assignment failed: ',
      publicationIdAssignedPrefix: 'Publication ID assigned: ',
      identifierAssigned: 'Identifier assignment completed.',
      unclassified: 'Unclassified'
    },
    paperCard: {
      noAbstract: 'No abstract provided.',
      openArticle: 'Open article',
      pdf: 'PDF'
    },
    paperDetail: {
      notFound: 'Paper not found · Incremental Findings',
      publishedArticle: 'Published paper',
      doiPending: 'DOI pending assignment',
      abstract: 'Abstract',
      noAbstract: 'No abstract provided.',
      viewPdf: 'View full PDF',
      downloadBibtex: 'Download BibTeX',
      backToDiscovery: 'Back to discovery'
    }
  }
} as const;

export function getSiteLang(input?: string | null): SiteLang {
  return input === 'en' ? 'en' : 'zh';
}

export function getSiteCopy(lang?: string | null) {
  return SITE_COPY[getSiteLang(lang)];
}
